version: '3.9'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql-apt
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_apt
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: gnuhhung317/smart-apt:latest
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-apt:3306/smart_apt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:


